compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.3.1.cjs
