enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.9.4.cjs
