name: Build image

permissions: read-all

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*' # glob for semver tags (including prereleases)
  pull_request:
    branches: [ master ]

jobs:
  call-build-image:
    uses: UW-Macrostrat/build-push/.github/workflows/build-push.yaml@main
    secrets: inherit
    with:
      context: .
      image: 'hub.opensciencegrid.org/macrostrat/rockd-website'
